apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: selenium-node2
  labels:
    run: selenium-node2
spec:
  replicas: 20
  selector:
    matchLabels:
      run: selenium-node2
  template:
    metadata:
      labels:
        run: selenium-node2
    spec:
      containers:
      - name: selenium-node2
        image: selenium/node-chrome-debug:3.141.59-gold
        ports:
          - containerPort: 5900
        env:
          - name: HUB_PORT_4444_TCP_ADDR
            value: "selenium-hub2"
          - name: HUB_PORT_4444_TCP_PORT
            value: "4444"
        resources:
          limits:
            memory: "1000Mi"
            cpu: ".5"